require_relative 'grruby/grruby'
require_relative 'grruby/tasks/GrFunctionsClasses'
require_relative 'rubyplot/scripting_backends/gr/plots'
require_relative 'rubyplot/figure'
require_relative 'rubyplot/scripting_backends/gr/plotspace'
